# template.yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Outyet Go API'
Resources:
  GoAPI:
    Type: AWS::Serverless::Function
    Properties:
      Handler: outyet
      Runtime: go1.x
      CodeUri: ./outyet.zip
      Events:
        Request:
          Type: Api
          Properties:
            Method: get
            Path: /{proxy+}
